name: manning_rf
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pandas=1.1.2
  - numpy
  - scikit-learn
  - swifter
  - ipympl
  - jupyterlab=2.2.8
  - pandas-profiling=2.9.0
  - ipython=7.18.1
  - h2o-py=3.30.1.3
  - mlxtend
  - seaborn
