name: manning_rf
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pandas=1.1.2
  - numpy=1.19.1
  - scikit-learn=0.23.2
  - swifter=1.0.6
  - ipympl=0.5.8
  - jupyterlab=2.2.8
  - pandas-profiling=2.9.0
  - ipython=17.18.1
  - h2o-py=3.30.1.3
  - mlxtend=0.17.3
  - seaborn=0.11.1
